# Generated by Django 4.2 on 2025-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_image_url_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='notions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='versions',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
